project:
  type: website
  output-dir: docs

website:
  title: "Yunqing Zhao"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: resume.qmd
        text: Resume
      - href: projects.qmd
        text: Projects
      - text: Blog
        menu:
         - href: hw1_questions.qmd
           text: HW1 - A/B Testing


format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
