<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.13">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Yunqing Zhao">
<meta name="dcterms.date" content="2026-05-24">

<title>MaxDiff Analysis of MSBA Class Preferences – Yunqing Zhao</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js" integrity="sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2" crossorigin="anonymous"></script><script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-ac077c1e730dfeb5e42400639d17284e.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-8fedf4b0b09d7e3efc607d46e5f6a2f0.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js" integrity="sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>


<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Yunqing Zhao</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../resume.html"> 
<span class="menu-text">Resume</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../projects.html"> 
<span class="menu-text">Projects</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-blog" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Blog</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-blog">    
        <li>
    <a class="dropdown-item" href="../hw1_questions.html">
 <span class="dropdown-text">HW1 - A/B Testing</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../hw2_questions.html">
 <span class="dropdown-text">HW2 - Replicate Causal Academic Work</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../MGTA_495_HW3/hw3_questions.html">
 <span class="dropdown-text">HW3 - MLE</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../MGTA495_HW4/hw4_questions.html">
 <span class="dropdown-text">HW4 – MaxDiff</span></a>
  </li>  
    </ul>
  </li>
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#the-data" id="toc-the-data" class="nav-link" data-scroll-target="#the-data">The Data</a>
  <ul class="collapse">
  <li><a href="#basic-descriptives" id="toc-basic-descriptives" class="nav-link" data-scroll-target="#basic-descriptives">Basic Descriptives</a></li>
  <li><a href="#sanity-check" id="toc-sanity-check" class="nav-link" data-scroll-target="#sanity-check">Sanity Check</a></li>
  <li><a href="#item-exposure" id="toc-item-exposure" class="nav-link" data-scroll-target="#item-exposure">Item Exposure</a></li>
  </ul></li>
  <li><a href="#counts-analysis" id="toc-counts-analysis" class="nav-link" data-scroll-target="#counts-analysis">Counts Analysis</a></li>
  <li><a href="#from-maxdiff-data-to-mnl-choices" id="toc-from-maxdiff-data-to-mnl-choices" class="nav-link" data-scroll-target="#from-maxdiff-data-to-mnl-choices">From MaxDiff Data to MNL Choices</a>
  <ul class="collapse">
  <li><a href="#likelihood-function" id="toc-likelihood-function" class="nav-link" data-scroll-target="#likelihood-function">Likelihood function</a></li>
  <li><a href="#mle-estimation" id="toc-mle-estimation" class="nav-link" data-scroll-target="#mle-estimation">MLE Estimation</a></li>
  </ul></li>
  <li><a href="#mnl-via-maximum-likelihood" id="toc-mnl-via-maximum-likelihood" class="nav-link" data-scroll-target="#mnl-via-maximum-likelihood">MNL via Maximum Likelihood</a></li>
  <li><a href="#mnl-via-bayesian-estimation" id="toc-mnl-via-bayesian-estimation" class="nav-link" data-scroll-target="#mnl-via-bayesian-estimation">MNL via Bayesian Estimation</a>
  <ul class="collapse">
  <li><a href="#tuning-the-sampler" id="toc-tuning-the-sampler" class="nav-link" data-scroll-target="#tuning-the-sampler">Tuning the Sampler</a></li>
  <li><a href="#final-mcmc-run" id="toc-final-mcmc-run" class="nav-link" data-scroll-target="#final-mcmc-run">Final MCMC Run</a></li>
  <li><a href="#posterior-summaries" id="toc-posterior-summaries" class="nav-link" data-scroll-target="#posterior-summaries">Posterior Summaries</a></li>
  </ul></li>
  <li><a href="#comparing-the-three-methods" id="toc-comparing-the-three-methods" class="nav-link" data-scroll-target="#comparing-the-three-methods">Comparing the Three Methods</a></li>
  <li><a href="#discussion" id="toc-discussion" class="nav-link" data-scroll-target="#discussion">Discussion</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">MaxDiff Analysis of MSBA Class Preferences</h1>
<p class="subtitle lead">Counts, MLE, and Bayesian estimation of the MNL model</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Yunqing Zhao </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">May 24, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<p>MaxDiff, also known as Best-Worst Scaling, is a survey method used to measure relative preferences between different items. Respondents repeatedly choose the most preferred and least preferred option from a small set of choices. In this survey, each screen showed four MSBA core classes, and respondents selected which class they liked the most and which they liked the least.</p>
<p>One reason MaxDiff is useful is that people are usually better at making comparisons than assigning consistent numeric ratings. Asking someone to pick a “best” and “worst” option forces clearer trade-offs and reduces the tendency for everyone to rate everything similarly.</p>
<p>In this blog, the ten items represent the ten core MSBA classes at UC San Diego Rady School of Management. The goal is to estimate students’ relative preferences for these classes using three different approaches: a simple counts analysis, a multinomial logit (MNL) model estimated with maximum likelihood, and a Bayesian version of the same MNL model using MCMC methods.</p>
<p>Although the three methods are based on different ideas, they should produce similar rankings of the classes. The main differences are in how they measure preference strength and how they capture uncertainty in the estimates.</p>
</section>
<section id="the-data" class="level2">
<h2 class="anchored" data-anchor-id="the-data">The Data</h2>
<p>The dataset contains responses from a MaxDiff survey about preferences for the ten core MSBA classes at UCSD Rady. Each respondent completed multiple choice tasks where they selected the most and least preferred class from a set of four options.</p>
<section id="basic-descriptives" class="level3">
<h3 class="anchored" data-anchor-id="basic-descriptives">Basic Descriptives</h3>
<p>Before doing any modeling, I first summarized the basic structure of the survey.</p>
<div id="ad4e4a3f" class="cell" data-execution_count="2">
<div class="cell-output cell-output-display" data-execution_count="2">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Statistic</th>
<th data-quarto-table-cell-role="th">Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>Number of respondents</td>
<td>85</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>Tasks per respondent</td>
<td>15</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>Items per task</td>
<td>4</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">3</th>
<td>Total labeled items</td>
<td>10</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>The survey included 85 respondents, and each respondent completed 15 MaxDiff tasks. Each task showed four options. The label file identifies ten official MSBA classes, so the later analysis focuses on those ten labeled items.</p>
</section>
<section id="sanity-check" class="level3">
<h3 class="anchored" data-anchor-id="sanity-check">Sanity Check</h3>
<p>Before using the data for any preference analysis, I wanted to make sure each MaxDiff task was recorded correctly. Since every task shows four classes, there should be exactly one class marked as the most preferred, one class marked as the least preferred, and two classes left unselected.</p>
<div id="92d29591" class="cell" data-execution_count="3">
<div class="cell-output cell-output-display" data-execution_count="3">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Check</th>
<th data-quarto-table-cell-role="th">Count</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>Valid tasks</td>
<td>680</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>Invalid tasks</td>
<td>595</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>The sanity check shows that 680 respondent-task combinations follow the expected MaxDiff structure, while 595 are flagged during the validation step. The main reason is that the raw survey file includes an unmatched item that does not appear in the class label file. Since the blog focuses on the ten labeled MSBA classes, I use the labeled class data for the remaining analysis.</p>
</section>
<section id="item-exposure" class="level3">
<h3 class="anchored" data-anchor-id="item-exposure">Item Exposure</h3>
<p>Finally, I checked how often each class appeared across the survey. In a balanced MaxDiff design, the exposure counts should be relatively similar across items so that no class has an unfair advantage simply from being shown more often.</p>
<div id="f893f826" class="cell" data-execution_count="4">
<div class="cell-output cell-output-display" data-execution_count="4">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Item</th>
<th data-quarto-table-cell-role="th">Class</th>
<th data-quarto-table-cell-role="th">Times Shown</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>1</td>
<td>MGTA 403 AI Math, Prog., &amp; Analytics (Summer w...</td>
<td>332</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>2</td>
<td>MGTA 464 SQL (Summer with Nijs)</td>
<td>340</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>3</td>
<td>MGTA 451 Marketing/Finance/Operations (Summer ...</td>
<td>326</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">3</th>
<td>4</td>
<td>MGTA 452 Large Data (Fall with Hansen)</td>
<td>338</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">4</th>
<td>5</td>
<td>MGTA 453 Business Analytics (Fall with August)</td>
<td>327</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">5</th>
<td>6</td>
<td>MGTA 444 Analytics Consulting (Winter with Pet...</td>
<td>323</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">6</th>
<td>7</td>
<td>MGTA 455 Customer Analytics (Winter with Nijs)</td>
<td>335</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">7</th>
<td>8</td>
<td>MGTA 454 Capstone Project (Spring with Advisor)</td>
<td>330</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">8</th>
<td>9</td>
<td>MGTA 495 Marketing Analytics (Spring with Yavo...</td>
<td>330</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">9</th>
<td>10</td>
<td>MGTA 457 Biz. Intelligence Systems (Fall with ...</td>
<td>334</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>The exposure counts are very similar across the ten classes, which suggests that the MaxDiff design was reasonably balanced. No class appears to have been shown more or less often than the others, so the preference estimates later in the analysis are less likely to be driven by unequal exposure.</p>
</section>
</section>
<section id="counts-analysis" class="level2">
<h2 class="anchored" data-anchor-id="counts-analysis">Counts Analysis</h2>
<p>For the counts analysis, I calculated how often each class was shown, how often it was picked as best, and how often it was picked as worst. I then used the difference between the best percentage and worst percentage as a simple score. This gives a quick first look at preferences before using the MNL model.</p>
<div id="f3726e39" class="cell" data-execution_count="5">
<div class="cell-output cell-output-display" data-execution_count="5">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Item</th>
<th data-quarto-table-cell-role="th">Class</th>
<th data-quarto-table-cell-role="th">times_shown</th>
<th data-quarto-table-cell-role="th">times_best</th>
<th data-quarto-table-cell-role="th">times_worst</th>
<th data-quarto-table-cell-role="th">pct_best</th>
<th data-quarto-table-cell-role="th">pct_worst</th>
<th data-quarto-table-cell-role="th">score</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">8</th>
<td>9</td>
<td>MGTA 495 Marketing Analytics (Spring with Yavo...</td>
<td>330</td>
<td>199</td>
<td>12</td>
<td>60.3</td>
<td>3.6</td>
<td>0.567</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">4</th>
<td>5</td>
<td>MGTA 453 Business Analytics (Fall with August)</td>
<td>327</td>
<td>143</td>
<td>55</td>
<td>43.7</td>
<td>16.8</td>
<td>0.269</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">6</th>
<td>7</td>
<td>MGTA 455 Customer Analytics (Winter with Nijs)</td>
<td>335</td>
<td>155</td>
<td>71</td>
<td>46.3</td>
<td>21.2</td>
<td>0.251</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">3</th>
<td>4</td>
<td>MGTA 452 Large Data (Fall with Hansen)</td>
<td>338</td>
<td>122</td>
<td>60</td>
<td>36.1</td>
<td>17.8</td>
<td>0.183</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">7</th>
<td>8</td>
<td>MGTA 454 Capstone Project (Spring with Advisor)</td>
<td>330</td>
<td>124</td>
<td>69</td>
<td>37.6</td>
<td>20.9</td>
<td>0.167</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>2</td>
<td>MGTA 464 SQL (Summer with Nijs)</td>
<td>340</td>
<td>111</td>
<td>56</td>
<td>32.6</td>
<td>16.5</td>
<td>0.162</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">9</th>
<td>10</td>
<td>MGTA 457 Biz. Intelligence Systems (Fall with ...</td>
<td>334</td>
<td>74</td>
<td>55</td>
<td>22.2</td>
<td>16.5</td>
<td>0.057</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">0</th>
<td>1</td>
<td>MGTA 403 AI Math, Prog., &amp; Analytics (Summer w...</td>
<td>332</td>
<td>76</td>
<td>90</td>
<td>22.9</td>
<td>27.1</td>
<td>-0.042</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>3</td>
<td>MGTA 451 Marketing/Finance/Operations (Summer ...</td>
<td>326</td>
<td>75</td>
<td>101</td>
<td>23.0</td>
<td>31.0</td>
<td>-0.080</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">5</th>
<td>6</td>
<td>MGTA 444 Analytics Consulting (Winter with Pet...</td>
<td>323</td>
<td>61</td>
<td>111</td>
<td>18.9</td>
<td>34.4</td>
<td>-0.155</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div id="4fb718b0" class="cell" data-execution_count="6">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="hw4_questions_files/figure-html/cell-7-output-1.png" width="763" height="468" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>The counts analysis shows a pretty clear ranking across the classes. Marketing Analytics stands out the most, with a much higher score than the other classes. It was chosen as “best” very often and only rarely selected as “worst.” Business Analytics and Customer Analytics also received strong scores overall.</p>
<p>Most of the middle-ranked classes still have positive scores, which suggests that students generally viewed them favorably. However, the differences between those classes are fairly small.</p>
<p>At the bottom of the ranking, AI Math, Marketing/Finance/Operations, and Analytics Consulting were selected as “worst” more often than “best,” which led to negative scores. Overall, the results suggest that students had stronger preferences for some classes than others, especially for Marketing Analytics.</p>
</section>
<section id="from-maxdiff-data-to-mnl-choices" class="level2">
<h2 class="anchored" data-anchor-id="from-maxdiff-data-to-mnl-choices">From MaxDiff Data to MNL Choices</h2>
<p>Each MaxDiff task can be viewed as a sequence of MNL choices. First, the respondent chooses the “best” item from the full set of four classes. Then, after removing the best item, the respondent chooses the “worst” item from the remaining three classes.</p>
<p>In the MNL model, each class is assigned a utility parameter that represents its relative preference. Classes with larger utility values are more likely to be selected as “best,” while classes with lower utility values are more likely to be selected as “worst.”</p>
<p>Because only utility differences matter in the softmax probabilities, the model is not fully identified unless one coefficient is fixed as a reference. In this analysis, I set the first class utility equal to zero and estimated the remaining coefficients relative to that baseline.</p>
<div id="3f8ee407" class="cell" data-execution_count="7">
<div class="cell-output cell-output-display" data-execution_count="7">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Record ID</th>
<th data-quarto-table-cell-role="th">Task</th>
<th data-quarto-table-cell-role="th">items</th>
<th data-quarto-table-cell-role="th">best_item</th>
<th data-quarto-table-cell-role="th">worst_item</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>69fb85fbd66b452e6decf4f7</td>
<td>1</td>
<td>[5, 7, 4, 1]</td>
<td>7</td>
<td>1</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>69fb85fbd66b452e6decf4f7</td>
<td>2</td>
<td>[8, 3, 10, 9]</td>
<td>10</td>
<td>8</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>69fb85fbd66b452e6decf4f7</td>
<td>3</td>
<td>[3, 5, 2, 6]</td>
<td>2</td>
<td>6</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">3</th>
<td>69fb85fbd66b452e6decf4f7</td>
<td>4</td>
<td>[6, 4, 8, 7]</td>
<td>7</td>
<td>6</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">4</th>
<td>69fb85fbd66b452e6decf4f7</td>
<td>5</td>
<td>[2, 9, 7, 1]</td>
<td>2</td>
<td>1</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div id="efa360ab" class="cell" data-execution_count="8">
<div class="cell-output cell-output-display" data-execution_count="8">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Check</th>
<th data-quarto-table-cell-role="th">Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>Number of valid choice tasks</td>
<td>680</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>After reshaping the data, each row now represents one respondent task combination. For every task, the dataset stores the four items that were shown, along with the item selected as best and the item selected as worst.</p>
<p>This structure is more convenient for the MNL model because the likelihood function can process one task at a time. The reshaped data also confirms that there are 680 valid choice tasks available for the estimation step.</p>
<section id="likelihood-function" class="level3">
<h3 class="anchored" data-anchor-id="likelihood-function">Likelihood function</h3>
<p>The next step is to write the likelihood function for the MNL model. Given a set of utility parameters, the likelihood measures how probable the observed best and worst choices are under the model.</p>
<p>For each task, the model first computes the probability of the observed best choice from the full set of four items. Then, after removing the best item, it computes the probability of the observed worst choice from the remaining three items using flipped utilities. The total log-likelihood is the sum across all tasks.</p>
<p>The likelihood function loops through the choice tasks one at a time. For each task, it computes the probability of the observed best choice and the probability of the observed worst choice. These probabilities are converted into log form and added together across all tasks.</p>
<p>I fixed the first utility parameter equal to zero so that the remaining coefficients can be interpreted relative to the reference class.</p>
</section>
<section id="mle-estimation" class="level3">
<h3 class="anchored" data-anchor-id="mle-estimation">MLE Estimation</h3>
<div id="e76537af" class="cell" data-execution_count="11">
<div class="cell-output cell-output-display" data-execution_count="11">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Item</th>
<th data-quarto-table-cell-role="th">Class</th>
<th data-quarto-table-cell-role="th">MLE Utility</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">8</th>
<td>9</td>
<td>MGTA 495 Marketing Analytics (Spring with Yavo...</td>
<td>1.630</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">4</th>
<td>5</td>
<td>MGTA 453 Business Analytics (Fall with August)</td>
<td>0.744</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">6</th>
<td>7</td>
<td>MGTA 455 Customer Analytics (Winter with Nijs)</td>
<td>0.656</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">3</th>
<td>4</td>
<td>MGTA 452 Large Data (Fall with Hansen)</td>
<td>0.555</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">7</th>
<td>8</td>
<td>MGTA 454 Capstone Project (Spring with Advisor)</td>
<td>0.443</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>2</td>
<td>MGTA 464 SQL (Summer with Nijs)</td>
<td>0.438</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">9</th>
<td>10</td>
<td>MGTA 457 Biz. Intelligence Systems (Fall with ...</td>
<td>0.236</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">0</th>
<td>1</td>
<td>MGTA 403 AI Math, Prog., &amp; Analytics (Summer w...</td>
<td>0.000</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>3</td>
<td>MGTA 451 Marketing/Finance/Operations (Summer ...</td>
<td>-0.067</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">5</th>
<td>6</td>
<td>MGTA 444 Analytics Consulting (Winter with Pet...</td>
<td>-0.239</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div id="f2542de4" class="cell" data-execution_count="12">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="hw4_questions_files/figure-html/cell-13-output-1.png" width="786" height="468" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>The MLE estimates are very similar to the earlier counts analysis. The same classes still appear near the top and bottom of the ranking, which suggests that the simple counts approach already captured most of the overall preference pattern in the data.</p>
<p>Marketing Analytics remains the strongest class by a fairly large margin, with the highest estimated utility in the model. Business Analytics and Customer Analytics also continue to receive relatively strong preference estimates.</p>
<p>At the lower end, Analytics Consulting and Marketing/Finance/Operations receive the smallest utility values. Their negative estimates suggest that respondents were less likely to choose them as best compared to the reference class.</p>
<p>One thing I noticed is that the MNL estimates create a little more separation between the classes than the counts scores did. Even though the rankings are similar overall, the utility estimates give a clearer sense of how strongly students preferred some classes over others.</p>
</section>
</section>
<section id="mnl-via-maximum-likelihood" class="level2">
<h2 class="anchored" data-anchor-id="mnl-via-maximum-likelihood">MNL via Maximum Likelihood</h2>
<p>The log-likelihood function was also defined in the previous section. Using that function, I estimated the MNL utility coefficients by maximum likelihood with the BFGS optimizer. The final negative log-likelihood value from the optimization is shown below.</p>
<div id="c2896daf" class="cell" data-execution_count="13">
<div class="cell-output cell-output-display" data-execution_count="13">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Statistic</th>
<th data-quarto-table-cell-role="th">Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>Final negative log-likelihood</td>
<td>1572.731</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div id="476bdb18" class="cell" data-execution_count="16">
<div class="cell-output cell-output-display" data-execution_count="16">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Item</th>
<th data-quarto-table-cell-role="th">Class</th>
<th data-quarto-table-cell-role="th">beta_hat</th>
<th data-quarto-table-cell-role="th">SE</th>
<th data-quarto-table-cell-role="th">Preference Share</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">8</th>
<td>9</td>
<td>MGTA 495 Marketing Analytics (Spring with Yavo...</td>
<td>1.630</td>
<td>0.061</td>
<td>0.284</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">4</th>
<td>5</td>
<td>MGTA 453 Business Analytics (Fall with August)</td>
<td>0.744</td>
<td>0.115</td>
<td>0.117</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">6</th>
<td>7</td>
<td>MGTA 455 Customer Analytics (Winter with Nijs)</td>
<td>0.656</td>
<td>0.098</td>
<td>0.107</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">3</th>
<td>4</td>
<td>MGTA 452 Large Data (Fall with Hansen)</td>
<td>0.555</td>
<td>0.127</td>
<td>0.097</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">7</th>
<td>8</td>
<td>MGTA 454 Capstone Project (Spring with Advisor)</td>
<td>0.443</td>
<td>0.262</td>
<td>0.087</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>2</td>
<td>MGTA 464 SQL (Summer with Nijs)</td>
<td>0.438</td>
<td>0.455</td>
<td>0.086</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">9</th>
<td>10</td>
<td>MGTA 457 Biz. Intelligence Systems (Fall with ...</td>
<td>0.236</td>
<td>0.093</td>
<td>0.070</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">0</th>
<td>1</td>
<td>MGTA 403 AI Math, Prog., &amp; Analytics (Summer w...</td>
<td>0.000</td>
<td>NaN</td>
<td>0.056</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>3</td>
<td>MGTA 451 Marketing/Finance/Operations (Summer ...</td>
<td>-0.067</td>
<td>0.178</td>
<td>0.052</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">5</th>
<td>6</td>
<td>MGTA 444 Analytics Consulting (Winter with Pet...</td>
<td>-0.239</td>
<td>0.343</td>
<td>0.044</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div id="0459e1e9" class="cell" data-execution_count="17">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="hw4_questions_files/figure-html/cell-18-output-1.png" width="772" height="468" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>The preference shares are easier to read than the raw utility estimates because they sum to 1 across the ten classes. A larger share means that the class receives a larger portion of the total estimated preference.</p>
<p>The MLE ranking is basically the same as the counts ranking from the previous section. Marketing Analytics is still clearly first, followed by Business Analytics and Customer Analytics. The bottom of the ranking is also the same, with Marketing/Finance/Operations and Analytics Consulting receiving the lowest preference shares.</p>
</section>
<section id="mnl-via-bayesian-estimation" class="level2">
<h2 class="anchored" data-anchor-id="mnl-via-bayesian-estimation">MNL via Bayesian Estimation</h2>
<p>For the Bayesian version, I fit the same MNL model but treat the utility coefficients as unknown parameters with a prior distribution. I use a weakly informative normal prior and then sample from the posterior using a random-walk Metropolis algorithm.</p>
<section id="tuning-the-sampler" class="level3">
<h3 class="anchored" data-anchor-id="tuning-the-sampler">Tuning the Sampler</h3>
<div id="95aa4363" class="cell" data-execution_count="22">
<div class="cell-output cell-output-display" data-execution_count="22">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">step_size</th>
<th data-quarto-table-cell-role="th">accept_rate</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>0.03</td>
<td>0.6695</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>0.05</td>
<td>0.4785</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>0.08</td>
<td>0.2780</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">3</th>
<td>0.12</td>
<td>0.1195</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">4</th>
<td>0.18</td>
<td>0.0210</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">5</th>
<td>0.25</td>
<td>0.0020</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>The tuning results show the expected tradeoff between step size and acceptance rate. Very small step sizes produced acceptance rates that were too high, while larger step sizes caused the sampler to reject almost all proposals.</p>
<p>A step size of 0.08 gave an acceptance rate of about 28%, which falls within the recommended range from the lecture notes. I therefore used this value for the final Metropolis-Hastings run.</p>
</section>
<section id="final-mcmc-run" class="level3">
<h3 class="anchored" data-anchor-id="final-mcmc-run">Final MCMC Run</h3>
<div id="08bbba42" class="cell" data-execution_count="23">
<div class="cell-output cell-output-display" data-execution_count="23">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Statistic</th>
<th data-quarto-table-cell-role="th">Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>Final acceptance rate</td>
<td>0.289</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>The final acceptance rate was about 28.9%, which falls within the recommended range from the lecture notes. This suggests that the Metropolis-Hastings sampler was reasonably well tuned and was exploring the posterior distribution without rejecting too many proposals.</p>
<div id="658c8d0d" class="cell" data-execution_count="24">
<div class="cell-output cell-output-display" data-execution_count="24">
<pre><code>(15000, 9)</code></pre>
</div>
</div>
<p>I discarded the first 25% of the MCMC draws as burn-in so that the remaining draws would better represent the stabilized posterior distribution. ### Trace Plots</p>
<div id="3afe27e2" class="cell" data-execution_count="25">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="hw4_questions_files/figure-html/cell-26-output-1.png" width="757" height="276" class="figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="hw4_questions_files/figure-html/cell-26-output-2.png" width="757" height="276" class="figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="hw4_questions_files/figure-html/cell-26-output-3.png" width="757" height="276" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>The trace plots look reasonably stable after burn-in and do not show a strong upward or downward drift over time. Instead, the chains fluctuate around fairly stable regions with regular random movement, which is the “fuzzy caterpillar” pattern discussed in the lecture notes.</p>
<p>This suggests that the Metropolis-Hastings sampler is exploring the posterior distribution rather than getting stuck in one location. Overall, the chains appear to have mixed reasonably well after burn-in.</p>
</section>
<section id="posterior-summaries" class="level3">
<h3 class="anchored" data-anchor-id="posterior-summaries">Posterior Summaries</h3>
<div id="8bcf4416" class="cell" data-execution_count="27">
<div class="cell-output cell-output-display" data-execution_count="27">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Item</th>
<th data-quarto-table-cell-role="th">Class</th>
<th data-quarto-table-cell-role="th">Posterior Mean Beta</th>
<th data-quarto-table-cell-role="th">Beta CI Low</th>
<th data-quarto-table-cell-role="th">Beta CI High</th>
<th data-quarto-table-cell-role="th">Posterior Mean Share</th>
<th data-quarto-table-cell-role="th">Share CI Low</th>
<th data-quarto-table-cell-role="th">Share CI High</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">8</th>
<td>9</td>
<td>MGTA 495 Marketing Analytics (Spring with Yavo...</td>
<td>1.642</td>
<td>1.351</td>
<td>1.950</td>
<td>0.284</td>
<td>0.243</td>
<td>0.330</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">4</th>
<td>5</td>
<td>MGTA 453 Business Analytics (Fall with August)</td>
<td>0.750</td>
<td>0.465</td>
<td>1.043</td>
<td>0.117</td>
<td>0.096</td>
<td>0.140</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">6</th>
<td>7</td>
<td>MGTA 455 Customer Analytics (Winter with Nijs)</td>
<td>0.669</td>
<td>0.366</td>
<td>0.972</td>
<td>0.108</td>
<td>0.088</td>
<td>0.129</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">3</th>
<td>4</td>
<td>MGTA 452 Large Data (Fall with Hansen)</td>
<td>0.564</td>
<td>0.309</td>
<td>0.855</td>
<td>0.097</td>
<td>0.080</td>
<td>0.116</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">1</th>
<td>2</td>
<td>MGTA 464 SQL (Summer with Nijs)</td>
<td>0.445</td>
<td>0.162</td>
<td>0.731</td>
<td>0.086</td>
<td>0.071</td>
<td>0.103</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">7</th>
<td>8</td>
<td>MGTA 454 Capstone Project (Spring with Advisor)</td>
<td>0.450</td>
<td>0.171</td>
<td>0.753</td>
<td>0.086</td>
<td>0.071</td>
<td>0.104</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">9</th>
<td>10</td>
<td>MGTA 457 Biz. Intelligence Systems (Fall with ...</td>
<td>0.250</td>
<td>-0.013</td>
<td>0.518</td>
<td>0.071</td>
<td>0.058</td>
<td>0.085</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">0</th>
<td>1</td>
<td>MGTA 403 AI Math, Prog., &amp; Analytics (Summer w...</td>
<td>0.000</td>
<td>0.000</td>
<td>0.000</td>
<td>0.055</td>
<td>0.044</td>
<td>0.067</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>3</td>
<td>MGTA 451 Marketing/Finance/Operations (Summer ...</td>
<td>-0.054</td>
<td>-0.335</td>
<td>0.243</td>
<td>0.052</td>
<td>0.043</td>
<td>0.064</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">5</th>
<td>6</td>
<td>MGTA 444 Analytics Consulting (Winter with Pet...</td>
<td>-0.231</td>
<td>-0.500</td>
<td>0.060</td>
<td>0.044</td>
<td>0.035</td>
<td>0.053</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div id="9f3b379e" class="cell" data-execution_count="28">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="hw4_questions_files/figure-html/cell-29-output-1.png" width="869" height="468" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<div id="13903580" class="cell" data-execution_count="29">
<div class="cell-output cell-output-display" data-execution_count="29">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Item</th>
<th data-quarto-table-cell-role="th">Class</th>
<th data-quarto-table-cell-role="th">Posterior Mean Beta</th>
<th data-quarto-table-cell-role="th">Posterior SD</th>
<th data-quarto-table-cell-role="th">MLE Beta</th>
<th data-quarto-table-cell-role="th">MLE SE</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">8</th>
<td>9</td>
<td>MGTA 495 Marketing Analytics (Spring with Yavo...</td>
<td>1.642</td>
<td>0.149</td>
<td>1.630</td>
<td>0.061</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">4</th>
<td>5</td>
<td>MGTA 453 Business Analytics (Fall with August)</td>
<td>0.750</td>
<td>0.145</td>
<td>0.744</td>
<td>0.115</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">6</th>
<td>7</td>
<td>MGTA 455 Customer Analytics (Winter with Nijs)</td>
<td>0.669</td>
<td>0.156</td>
<td>0.656</td>
<td>0.098</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">3</th>
<td>4</td>
<td>MGTA 452 Large Data (Fall with Hansen)</td>
<td>0.564</td>
<td>0.139</td>
<td>0.555</td>
<td>0.127</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">7</th>
<td>8</td>
<td>MGTA 454 Capstone Project (Spring with Advisor)</td>
<td>0.450</td>
<td>0.147</td>
<td>0.443</td>
<td>0.262</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>2</td>
<td>MGTA 464 SQL (Summer with Nijs)</td>
<td>0.445</td>
<td>0.142</td>
<td>0.438</td>
<td>0.455</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">9</th>
<td>10</td>
<td>MGTA 457 Biz. Intelligence Systems (Fall with ...</td>
<td>0.250</td>
<td>0.133</td>
<td>0.236</td>
<td>0.093</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">0</th>
<td>1</td>
<td>MGTA 403 AI Math, Prog., &amp; Analytics (Summer w...</td>
<td>0.000</td>
<td>0.000</td>
<td>0.000</td>
<td>NaN</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>3</td>
<td>MGTA 451 Marketing/Finance/Operations (Summer ...</td>
<td>-0.054</td>
<td>0.147</td>
<td>-0.067</td>
<td>0.178</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">5</th>
<td>6</td>
<td>MGTA 444 Analytics Consulting (Winter with Pet...</td>
<td>-0.231</td>
<td>0.145</td>
<td>-0.239</td>
<td>0.343</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>The Bayesian posterior means are very similar to the earlier MLE estimates. Marketing Analytics still receives the largest estimated share of preference by a fairly wide margin, while Analytics Consulting and Marketing/Finance/Operations remain near the bottom of the ranking.</p>
<p>The credible intervals provide additional information about uncertainty in the estimates. Some of the middle-ranked classes have overlapping intervals, which suggests that the differences between them may not be very large. In contrast, Marketing Analytics stands out much more clearly from the rest of the classes.</p>
<p>Overall, the Bayesian results tell a very similar story to the MLE results. The posterior means are generally close to the MLE point estimates, and the posterior standard deviations are also fairly similar to the MLE standard errors. The overall ranking pattern remains stable across methods, which is reassuring since both approaches are fitting the same underlying MNL model.</p>
</section>
</section>
<section id="comparing-the-three-methods" class="level2">
<h2 class="anchored" data-anchor-id="comparing-the-three-methods">Comparing the Three Methods</h2>
<p>The final step is to compare the results from all three approaches side by side. Even though the counts analysis, MLE model, and Bayesian model are based on different ideas, they should still produce broadly similar preference patterns if the results are stable.</p>
<div id="6f95c20b" class="cell" data-execution_count="30">
<div class="cell-output cell-output-display" data-execution_count="30">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Item</th>
<th data-quarto-table-cell-role="th">Class</th>
<th data-quarto-table-cell-role="th">Counts Score</th>
<th data-quarto-table-cell-role="th">MLE Share</th>
<th data-quarto-table-cell-role="th">Bayes Share</th>
<th data-quarto-table-cell-role="th">Counts Rank</th>
<th data-quarto-table-cell-role="th">MLE Rank</th>
<th data-quarto-table-cell-role="th">Bayes Rank</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">8</th>
<td>9</td>
<td>MGTA 495 Marketing Analytics (Spring with Yavo...</td>
<td>0.567</td>
<td>0.284</td>
<td>0.284</td>
<td>1</td>
<td>1</td>
<td>1</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">4</th>
<td>5</td>
<td>MGTA 453 Business Analytics (Fall with August)</td>
<td>0.269</td>
<td>0.117</td>
<td>0.117</td>
<td>2</td>
<td>2</td>
<td>2</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">6</th>
<td>7</td>
<td>MGTA 455 Customer Analytics (Winter with Nijs)</td>
<td>0.251</td>
<td>0.107</td>
<td>0.108</td>
<td>3</td>
<td>3</td>
<td>3</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">3</th>
<td>4</td>
<td>MGTA 452 Large Data (Fall with Hansen)</td>
<td>0.183</td>
<td>0.097</td>
<td>0.097</td>
<td>4</td>
<td>4</td>
<td>4</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">7</th>
<td>8</td>
<td>MGTA 454 Capstone Project (Spring with Advisor)</td>
<td>0.167</td>
<td>0.087</td>
<td>0.086</td>
<td>5</td>
<td>5</td>
<td>5</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>2</td>
<td>MGTA 464 SQL (Summer with Nijs)</td>
<td>0.162</td>
<td>0.086</td>
<td>0.086</td>
<td>6</td>
<td>6</td>
<td>5</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">9</th>
<td>10</td>
<td>MGTA 457 Biz. Intelligence Systems (Fall with ...</td>
<td>0.057</td>
<td>0.070</td>
<td>0.071</td>
<td>7</td>
<td>7</td>
<td>7</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">0</th>
<td>1</td>
<td>MGTA 403 AI Math, Prog., &amp; Analytics (Summer w...</td>
<td>-0.042</td>
<td>0.056</td>
<td>0.055</td>
<td>8</td>
<td>8</td>
<td>8</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>3</td>
<td>MGTA 451 Marketing/Finance/Operations (Summer ...</td>
<td>-0.080</td>
<td>0.052</td>
<td>0.052</td>
<td>9</td>
<td>9</td>
<td>9</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">5</th>
<td>6</td>
<td>MGTA 444 Analytics Consulting (Winter with Pet...</td>
<td>-0.155</td>
<td>0.044</td>
<td>0.044</td>
<td>10</td>
<td>10</td>
<td>10</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div id="addc89b5" class="cell" data-execution_count="31">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="hw4_questions_files/figure-html/cell-32-output-1.png" width="1757" height="597" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>Even though the three approaches are built differently, they end up giving a very similar ranking overall. Marketing Analytics stays clearly at the top in every method, while Analytics Consulting remains at the bottom. That consistency makes the main preference pattern look pretty stable across the analyses.</p>
<p>Most of the small differences happen in the middle of the ranking. For example, SQL and Capstone are extremely close in both the MLE and Bayesian results, so their order changes slightly depending on the method. Since their estimated shares are nearly the same, those changes do not seem very meaningful.</p>
<p>The counts analysis works well as a simple summary, but the MNL models make fuller use of the survey information. Instead of only looking at which class was picked as best or worst, the MNL approach also uses information from the other classes that appeared in the same choice task but were not selected.</p>
<p>The Bayesian model tells almost the same story as the MLE model, but it adds uncertainty estimates in a more natural way through posterior distributions and credible intervals. I found the Bayesian results especially helpful for seeing which differences between classes were large and which ones were probably small.</p>
</section>
<section id="discussion" class="level2">
<h2 class="anchored" data-anchor-id="discussion">Discussion</h2>
<p>Across all three approaches, the overall preference pattern turned out to be consistent. Marketing Analytics was clearly the most preferred class in every analysis, while Analytics Consulting stayed near the bottom throughout. Business Analytics and Customer Analytics also performed strongly across the methods. One thing I found interesting was that most of the disagreement between methods only happened in the middle of the ranking, where several classes had fairly similar preference levels.</p>
<p>The counts analysis was useful as a quick descriptive summary since it was simple and easy to interpret. It gave a fast overview of which classes students tended to like or dislike most. However, the MNL models used the survey data more fully by modeling the actual choice process rather than only counting the final best and worst selections. In the MNL framework, even the classes that were shown but not chosen still contributed information to the estimates.</p>
<p>The MLE and Bayesian versions of the MNL model ended up producing very similar rankings and preference shares. The Bayesian approach was especially helpful because it provided credible intervals and posterior distributions, which made it easier to understand uncertainty in the estimates.</p>
<p>At the same time, there are some important limitations to keep in mind. The survey responses came from a relatively small and self-selected group of MSBA students, so the results may not generalize beyond this population. Students at different stages of the program may also value courses differently depending on their background, internship experience, or career goals. In addition, the way classes were presented in the survey could have influenced some of the choices.</p>
<p>If I had more time, I would probably expand the survey to include alumni and students from multiple MSBA cohorts instead of only the current group of respondents. A larger and more diverse sample could give a more reliable picture of long-term course preferences across the program. It would also be interesting to explore whether students with different career goals — such as marketing, consulting, or technical analytics — value the classes differently.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>